# Generated by Django 5.0.2 on 2024-03-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
