# Generated by Django 5.0.2 on 2024-03-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0008_alter_messages_receiver_alter_messages_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='checkmessage',
            field=models.BooleanField(default=True),
        ),
    ]
