# Generated by Django 5.0.2 on 2024-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0009_messages_checkmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='hashmessage',
            field=models.CharField(default='', max_length=512),
        ),
    ]
