# Generated by Django 5.0.3 on 2024-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0011_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.BigIntegerField(max_length=512),
        ),
        migrations.AlterField(
            model_name='account',
            name='public_key',
            field=models.BigIntegerField(max_length=512),
        ),
    ]
