# Generated by Django 5.0.3 on 2024-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0012_alter_account_private_key_alter_account_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='public_key',
            field=models.BigIntegerField(),
        ),
    ]
