# Generated by Django 5.0.3 on 2024-03-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0013_alter_account_private_key_alter_account_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='n',
            field=models.BigIntegerField(default=0),
        ),
    ]
