# Generated by Django 5.0.3 on 2024-03-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0014_account_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='n',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AlterField(
            model_name='account',
            name='public_key',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
