# Generated by Django 5.0.3 on 2024-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0015_alter_account_n_alter_account_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='n',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='account',
            name='public_key',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='messages',
            name='checkmessage',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='hashmessage',
            field=models.CharField(max_length=512),
        ),
    ]
