# Generated by Django 5.0.3 on 2024-03-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0016_alter_account_n_alter_account_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='hashmessage',
            new_name='signature',
        ),
    ]
