# Generated by Django 5.0.3 on 2024-03-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0017_rename_hashmessage_messages_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='senderPublic',
            field=models.CharField(default='', max_length=512),
        ),
    ]
