# Generated by Django 5.0.3 on 2024-03-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0019_alter_messages_senderpublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiverPublic',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
