# Generated by Django 5.0.3 on 2024-03-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0022_alter_messages_checkmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='mode',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
