# Generated by Django 5.0.3 on 2024-03-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoweb', '0023_messages_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='n',
        ),
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='account',
            name='public_key',
            field=models.CharField(max_length=1024),
        ),
    ]
